CREATE EXTERNAL TABLE IF NOT EXISTS ddb_ygg_confirming_operacion ( 
    Item struct<
        empRut:struct<N:string>,
        pgcId:struct<N:string>,
        comprobante:struct<L:array<struct< 
            M:struct<
                codigo:struct<S:string>,
                fechas:struct<M:struct<
                    creacion:struct<S:string>,
                    nomina:struct<S:string>,
                    operacion:struct<S:string>
                >>,
                link:struct<S:string>,
                montoFactura:struct<N:string>,
                motivoRechazo:struct<S:string>,
                proveedorNombre:struct<S:string>,
                proveedorRut:struct<N:string>
            >
        >>>,
        detalle:struct<M:struct<
            clienteRazonSocial:struct<S:string>,
            clienteRut:struct<N:string>,
            estado:struct<M:struct<
                id:struct<N:string>,
                nombre:struct<S:string>
            >>,
            fechas:struct<M:struct<
                curso:struct<S:string>,
                ingreso:struct<S:string>,
                termino:struct<S:string>
            >>,
            montos:struct<M:struct<
                anticipo:struct<N:string>,
                aplicaciones:struct<N:string>,
                comision:struct<N:string>,
                diferenciaPrecio:struct<N:string>,
                excedentes:struct<N:string>,
                gestionLegalAdministrativa:struct<N:string>,
                giro:struct<N:string>,
                iva:struct<N:string>,
                mora:struct<N:string>,
                total:struct<N:string>
            >>,
            saldoCredito:struct<N:string>,
            subProducto:struct<M:struct<
                id:struct<N:string>,
                nombre:struct<S:string>
            >>
        >>,
        dtes:struct<L:array<struct< 
            M:struct<
                emisorRazonSocial:struct<S:string>,
                emisorRut:struct<N:string>,
                fechas:struct<M:struct<
                    emision:struct<S:string>,
                    vencimiento:struct<S:string>,
                    vencimientoOriginal:struct<S:string>
                >>,
                folio:struct<N:string>,
                montos:struct<M:struct<
                    anticipo:struct<N:string>,
                    diferenciaPrecio:struct<N:string>,
                    excedentes:struct<N:string>,
                    giro:struct<N:string>,
                    total:struct<N:string>
                >>,
                receptorRazonSocial:struct<S:string>,
                receptorRut:struct<N:string>,
                tipoDte:struct<N:string>
            >
        >>>,
        empRut_fechaSolicitud:struct<S:string>,
        empRut_fechaSolicitud_estado:struct<S:string>,
        empRut_tipoConfirming:struct<S:string>,
        empRut_tipoConfirming_estado:struct<S:string>,
        estadoPago:struct<M:struct<
            idCxCConfirming:struct<N:string>,
            monto:struct<N:string>,
            montoPendiente:struct<N:string>,
            montoUtilizado:struct<N:string>,
            rut:struct<N:string>
        >>,   
        fechaActualizacion:struct<S:string>,
        fechaSolicitud:struct<S:string>,
        firmantes:struct<L:array<struct< 
            M:struct<
                estado:struct<S:string>,
                fechaFirma:struct<S:string>,
                nombre:struct<S:string>,
                rut:struct<N:string>
            >
        >>>,
        rutaArchivo:struct<S:string>,
        simId:struct<N:string>,
        subOperaciones:struct<M:struct<
            datos:struct<S:string>
        >>,
        tipoConfirming:struct<S:string>        
    >
)
ROW FORMAT SERDE 'org.openx.data.jsonserde.JsonSerDe'
LOCATION 's3://destination-guou-bucket-master/ygg-confirming-operacion/AWSDynamoDB/01673794853252-11b4c4ef/data/'
TBLPROPERTIES ( 'has_encrypted_data'='true');
