CREATE EXTERNAL TABLE IF NOT EXISTS ddb_ygg_financiamiento_operacion ( 
    Item struct<
        empRut:struct<N:string>,
        pgcId:struct<N:string>,
        detalle:struct<M:struct<
            aprobacionRiesgo:struct<BOOL:string>,
            cantidadDocumentos:struct<N:string>,
            emisorRut:struct<N:string>,
            estado:struct<M:struct<
                id:struct<N:string>,
                nombre:struct<S:string>
            >>,
            fechaOtorgamiento:struct<S:string>,
            montos:struct<M:struct<
               anticipo:struct<N:string>, 
               aplicaciones:struct<N:string>,
               comision:struct<N:string>,
               diferenciaPrecio:struct<N:string>,
               excedentes:struct<N:string>,
               gestionLegalAdministrativa:struct<N:string>,
               giro:struct<N:string>,
               iva:struct<N:string>,
               total:struct<N:string>
            >>,
            porcentajeAnticipo:struct<N:string>,
            tasa:struct<N:string>
        >>,
        dtes:struct<L:array<struct<
            M:struct<
                fechas:struct<M:struct<
                    emision:struct<S:string>,
                    prorroga:struct<S:string>,
                    vencimiento:struct<S:string>
                >>,
                folio:struct<N:string>,
                montos:struct<M:struct<
                    anticipo:struct<N:string>,
                    diferenciaPrecio:struct<N:string>,
                    excedentes:struct<N:string>,
                    giro:struct<N:string>,
                    total:struct<N:string>
                >>,
                observacion:struct<S:string>,
                receptorRazonSocial:struct<S:string>,
                receptorRut:struct<N:string>,
                tipoDte:struct<N:string>
            >
        >>>,
        empRut_estado:struct<S:string>,
        empRut_tipoFinanciamiento:struct<S:string>,
        empRut_tipoFinanciamiento_estado:struct<S:string>,
        estadoNombre:struct<S:string>,
        fechaActualizacion:struct<S:string>,
        fechaCreacionPGC:struct<S:string>,
        fechaSolicitud:struct<S:string>,
        giro:struct<L:array<struct<
            M:struct<
                cliente:struct<M:struct<
                    nombre:struct<S:string>,
                    rut:struct<N:string>
                >>,
                codigo:struct<N:string>,
                destinatario:struct<M:struct<
                    email:struct<S:string>,
                    nombre:struct<S:string>,
                    rut:struct<S:string>
                >>,
                moneda:struct<M:struct<
                    id:struct<N:string>,
                    nombre:struct<S:string>
                >>,
                montoGiro:struct<N:string>,
                montoGiroPadre:struct<N:string>,
                tipoId:struct<N:string>,
                transferencia:struct<M:struct<
                    banco:struct<M:struct<
                        id:struct<N:string>,
                        nombre:struct<S:string>
                    >>,
                    fecha:struct<S:string>,
                    numero:struct<S:string>,
                    tipo:struct<S:string>
                >>
            >
        >>>,
        rutaArchivo:struct<S:string>,
        simId:struct<N:string>,
        tipoFinanciamiento:struct<S:string>
    >
)
ROW FORMAT SERDE 'org.openx.data.jsonserde.JsonSerDe'
LOCATION 's3://destination-guou-bucket-master/ygg-financiamiento-operacion/AWSDynamoDB/01673794853798-52d333d1/data/'
TBLPROPERTIES ( 'has_encrypted_data'='true');