CREATE EXTERNAL TABLE IF NOT EXISTS ddb_ygg_empresas ( 
    Item struct<
        rut:struct<N:string>,
        activo:struct<N:string>,
        altaLegal:struct<M:struct<
            estado:struct<S:string>,
            pgcId:struct<N:string>
        >>,
        caracteristicasContribuyentes:struct<L:array<struct<
            M:struct<
                caracteristica:struct<S:string>,
                fechaInicio:struct<S:string>
            >
        >>>,
        cuentasBancarias:struct<L:array<struct<
            M:struct<
                banco:struct<S:string>,
                bancoId:struct<N:string>,
                correo:struct<S:string>,
                fechaCreacion:struct<S:string>,
                fechaModificacion:struct<S:string>,
                nombreCuenta:struct<S:string>,
                numeroCuenta:struct<S:string>,
                pgcId:struct<N:string>,
                tipoCuenta:struct<S:string>,
                tipoCuentaId:struct<N:string>
            >
        >>>,
        empresaUnDia:struct<BOOL:string>,
        fechaCreacion:struct<S:string>,
        fechaModificacion:struct<S:string>,
        flujoLegal:struct<M:struct<
            estado:struct<S:string>
        >>,
        jsonLegalBot:struct<M:struct<
            auth:struct<BOOL:string>,
            data:struct<M:struct<
                estado:struct<M:struct<
                    rut:struct<S:string>,
                    ejecutivo:struct<S:string>,
                    estado:struct<S:string>,
                    fecha:struct<S:string>,
                    id:struct<N:string>,
                    preEstudio:struct<S:string>,
                    razonSocial:struct<S:string>
                >>,
                estudio:struct<M:struct<
                    rut:struct<S:string>,
                    customer:struct<S:string>,
                    disuelto:struct<BOOL:string>,
                    errorExtraccion:struct<BOOL:string>,
                    errorFatal:struct<BOOL:string>,
                    fechaCambioAdministracion:struct<S:string>,
                    fechaEstudio:struct<S:string>,
                    mensajes:struct<L:string>,
                    modificado:struct<BOOL:string>,
                    penta:struct<M:struct<
                        rut:struct<S:string>,
                        administradores:struct<L:string>,
                        algunaEncontrada:struct<BOOL:string>,
                        disuelto:struct<BOOL:string>,
                        facultades:struct<L:string>,
                        matrizProductos:struct<L:string>,
                        preAprobado:struct<BOOL:string>,
                        razonSocial:struct<S:string>
                    >>,
                    preAprobado:struct<BOOL:string>,
                    prestudios:struct<L:string>,
                    tipoSociedad:struct<S:string>,
                    transformado:struct<BOOL:string>,
                    ultimaModificacion:struct<S:string>
                >>,
                id:struct<N:string>,
                ok:struct<BOOL:string>
            >>,
            mensaje:struct<S:string>,
            ok:struct<BOOL:string>
        >>,
        listadoRepresentantesLegales:struct<L:array<struct<
            M:struct<
                rut:struct<N:string>,
                fechaCreacion:struct<S:string>,
                nombre:struct<S:string>,
                vigente:struct<BOOL:string>
            >
        >>>,
        nombreFantasia:struct<S:string>,
        procesosAutenticacion:struct<M:struct<
            estado:struct<S:string>,
            procesoFin:struct<S:string>,
            procesoInicio:struct<S:string>
        >>,
        procesosCarpetaTributaria:struct<M:struct<
            estado:struct<S:string>,
            procesoFin:struct<S:string>,
            procesoInicio:struct<S:string>
        >>,
        procesosExtraccionCesion:struct<M:struct<
            estado:struct<S:string>,
            procesoFin:struct<S:string>,
            procesoInicio:struct<S:string>
        >>,
        procesosExtraccionDte:struct<M:struct<
            estado:struct<S:string>,
            procesoFin:struct<S:string>,
            procesoInicio:struct<S:string>
        >>,
        razonSocial:struct<S:string>,
        representanteLegal:struct<M:struct<
            rut:struct<N:string>,
            fechaCreacion:struct<S:string>,
            nombre:struct<S:string>,
            rutaCertificado:struct<S:string>,
            siiPassword:struct<S:string>,
            usuarioCreacion:struct<S:string>,
            vigente:struct<BOOL:string>
        >>,
        siiPassword:struct<S:string>,
        usuarios:struct<M:struct<
            M:struct<
                activo:struct<BOOL:string>,
                cargo:struct<S:string>,
                rolId:struct<S:string>
            >
        >>
    >
)
ROW FORMAT SERDE 'org.openx.data.jsonserde.JsonSerDe'
LOCATION 's3://destination-guou-bucket-master/ygg-empresas/AWSDynamoDB/01674399712598-9a36535b/data/'
TBLPROPERTIES ( 'has_encrypted_data'='true')
