CREATE EXTERNAL TABLE IF NOT EXISTS ddb_ygg_alta_legal_solicitud ( 
    Item struct<
        empRut:struct<N:string>,
        pgcId:struct<N:string>,
        condicionesContrato:struct<M:struct<
            fechaActualizacion:struct<S:string>,
            fechaCreacion:struct<S:string>,
            firmantes:struct<L:array<struct<
                M:struct<
                    combinaciones:struct<L:array<struct<
                        M:struct<
                            grupo:struct<S:string>,
                            id:struct<N:string>,
                            participantes:struct<L:array<struct<
                                M:struct<
                                    clasificacion:struct<S:string>,
                                    email:struct<S:string>,
                                    id:struct<N:string>,
                                    numeroDocumentoIdentidad:struct<S:string>,
                                    razonSocial:struct<S:string>
                                >
                            >>>
                        >
                    >>>,
                    contratos:struct<L:array<struct<
                        M:struct<
                            id:struct<N:string>,
                            nombre:struct<S:string>
                        >,
                        M:struct<
                            id:struct<N:string>,
                            nombre:struct<S:string>
                        >,
                        M:struct<
                            id:struct<N:string>,
                            nombre:struct<S:string>
                        >,
                        M:struct<
                            id:struct<N:string>,
                            nombre:struct<S:string>
                        >
                    >>>
                >
            >>>,
            numeroDocumentoIdentidad:struct<S:string>,
            pgcSolicitudId:struct<N:string>,
            razonSocial:struct<S:string>
        >>,
        contratoLink:struct<S:string>,
        documentos:struct<L:array<struct<
                M:struct<
                    estado:struct<S:string>,
                    fechaActualizacion:struct<S:string>,
                    fechaCreacion:struct<S:string>,
                    id:struct<N:string>,
                    link:struct<S:string>,
                    nombre:struct<S:string>,
                    observacion:struct<S:string>,
                    tipoId:struct<N:string>
                >
        >>>,
        estado:struct<S:string>,
        fechaActualizacion:struct<S:string>,
        fechaSolicitud:struct<S:string>,
        firmantesGrupoContrato:struct<L:array<struct<
            M:struct<
                firmantes:struct<L:array<struct<
                    M:struct<
                        pgcId:struct<N:string>,
                        ciudadId:struct<N:string>,
                        comunaId:struct<N:string>,
                        direccionCalle:struct<S:string>,
                        direccionNumero:struct<N:string>,
                        email:struct<S:string>,
                        estadoCivilId:struct<N:string>,
                        numeroDocumentoIdentidad:struct<S:string>,
                        paisId:struct<N:string>,
                        profesion:struct<S:string>,
                        razonSocial:struct<S:string>,
                        regionId:struct<N:string>
                    >
                >>>,
                grupoContrato:struct<L:array<struct<
                    M:struct<
                        id:struct<N:string>,
                        nombre:struct<S:string>
                    >
                >>>
            >
        >>>,
        observacion:struct<S:string>,
        producto:struct<SS:string>,
        rol:struct<S:string>
    >
)
ROW FORMAT SERDE 'org.openx.data.jsonserde.JsonSerDe'
LOCATION 's3://destination-guou-bucket-master/DynamoDB/ygg-alta-legal-solicitud/AWSDynamoDB/01673531361886-2bab125b/data/'
TBLPROPERTIES ( 'has_encrypted_data'='true')