CREATE EXTERNAL TABLE IF NOT EXISTS ddb_ygg_financiamiento_operacion_dte ( 
    Item struct<
        receptorRut:struct<N:string>,
        emisorRut_folio_tipoDte:struct<S:string>,
        detalle:struct<M:struct<
            receptorRut:struct<N:string>,
            emisorRut:struct<N:string>,
            estado:struct<M:struct<
                id:struct<N:string>,
                nombre:struct<S:string>
            >>,
            fechas:struct<M:struct<
                emision:struct<S:string>,
                prorroga:struct<S:string>,
                vencimiento:struct<S:string>
            >>,
            folio:struct<N:string>,
            montos:struct<M:struct<
                anticipo:struct<N:string>,
                diferenciaPrecio:struct<N:string>,
                excedentes:struct<N:string>,
                giro:struct<N:string>,
                total:struct<N:string>
            >>,
            observacion:struct<S:string>,
            pgcId:struct<N:string>,
            receptorRazonSocial:struct<S:string>,
            tipoDte:struct<N:string>,
            tipoFinanciamiento:struct<S:string>
        >>,
        emisorRazonSocial:struct<S:string>,
        emisorRut:struct<N:string>,
        empRut:struct<N:string>,
        empRut_estado:struct<S:string>,
        fechaVencimiento:struct<S:string>,
        recaudaciones:struct<M:struct<
            datos1:struct<M:struct<
                diasMora:struct<N:string>,
                documento:struct<M:struct<
                    codigo:struct<N:string>,
                    id:struct<N:string>,
                    tipo:struct<S:string>
                >>,
                emisor:struct<M:struct<
                    nombre:struct<S:string>,
                    rut:struct<S:string>
                >>,
                fechas:struct<M:struct<
                    creacion:struct<S:string>,
                    otorgamiento:struct<S:string>,
                    pago:struct<S:string>,
                    vencimiento:struct<S:string>
                >>,
                folio:struct<N:string>,
                montos:struct<M:struct<
                    capitalAmortizado:struct<N:string>,
                    documentoFactorizado:struct<N:string>,
                    pago:struct<N:string>,
                    reajustePago:struct<N:string>,
                    restante:struct<N:string>,
                    totalRecaudado:struct<N:string>
                >>,
                origen:struct<S:string>,
                pgcId:struct<N:string>,
                receptor:struct<M:struct<
                    nombre:struct<S:string>,
                    rut:struct<S:string>
                >>,
                responsablePago:struct<S:string>,
                tasa:struct<N:string>,
                tipoOperacion:struct<S:string>,
                tipoPago:struct<S:string>,
                valorMonedaOperacion:struct<S:string>,
                valorOperacion:struct<N:string>
            >>,
            datos2:struct<M:struct<
                diasMora:struct<N:string>,
                documento:struct<M:struct<
                    codigo:struct<N:string>,
                    id:struct<N:string>,
                    tipo:struct<S:string>
                >>,
                emisor:struct<M:struct<
                    nombre:struct<S:string>,
                    rut:struct<S:string>
                >>,
                fechas:struct<M:struct<
                    creacion:struct<S:string>,
                    otorgamiento:struct<S:string>,
                    pago:struct<S:string>,
                    vencimiento:struct<S:string>
                >>,
                folio:struct<N:string>,
                montos:struct<M:struct<
                    capitalAmortizado:struct<N:string>,
                    documentoFactorizado:struct<N:string>,
                    pago:struct<N:string>,
                    reajustePago:struct<N:string>,
                    restante:struct<N:string>,
                    totalRecaudado:struct<N:string>
                >>,
                origen:struct<S:string>,
                pgcId:struct<N:string>,
                receptor:struct<M:struct<
                    nombre:struct<S:string>,
                    rut:struct<S:string>
                >>,
                responsablePago:struct<S:string>,
                tasa:struct<N:string>,
                tipoOperacion:struct<S:string>,
                tipoPago:struct<S:string>,
                valorMonedaOperacion:struct<S:string>,
                valorOperacion:struct<N:string>
            >>
        >>,
        receptorRut_emisorRut:struct<S:string>,
        receptorRut_hasRecaudacion:struct<S:string>,
        receptorRut_tipoFinanciamiento:struct<S:string>
    >
)
ROW FORMAT SERDE 'org.openx.data.jsonserde.JsonSerDe'
LOCATION 's3://destination-guou-bucket-master/ygg-financiamiento-operacion-dte/AWSDynamoDB/01673794853877-0ad68ceb/data/'
TBLPROPERTIES ( 'has_encrypted_data'='true');